clear all
clc

run ../proc_0true.tf
run ../proc_1true.tf

figure(1)
plot3(element_1(:,1),element_1(:,2),element_1(:,3),'*b',...
element_2(:,1),element_2(:,2),element_2(:,3),'*r',...
element_3(:,1),element_3(:,2),element_3(:,3),'*b',...
element_4(:,1),element_4(:,2),element_4(:,3),'*b',...
element_5(:,1),element_5(:,2),element_5(:,3),'*b',...
element_6(:,1),element_6(:,2),element_6(:,3),'*b',...
element_7(:,1),element_7(:,2),element_7(:,3),'*b',...
element_8(:,1),element_8(:,2),element_8(:,3),'*b',...
element_9(:,1),element_9(:,2),element_9(:,3),'*b')

xlabel("xaxis")
ylabel("yaxis")
zlabel("zaxis")
         
